name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-2022
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          %windir%\system32\cmd.exe /c Downloads.bat

      - name: Download AnyDesk
        run: |
          Invoke-WebRequest -Uri "https://download.anydesk.com/AnyDesk.exe" -OutFile "D:\\a\\Ballooppower\\Ballooppower\\AnyDesk.exe"

      - name: Install AnyDesk
        run: |
          Start-Process -FilePath "D:\\a\\Ballooppower\\Ballooppower\\AnyDesk.exe" -ArgumentList "/install" -NoNewWindow -Wait -Verb RunAs
          Start-Sleep -Seconds 10

      - name: Configure AnyDesk
        run: |
          $password = "Hayat7014@"
          $configPath = "$env:APPDATA\\AnyDesk\\ad.ini"
          if (-Not (Test-Path $configPath)) {
            New-Item -Path $configPath -ItemType File -Force
          }
          Add-Content -Path $configPath -Value "[security]"
          Add-Content -Path $configPath -Value "password=$password"
          Add-Content -Path $configPath -Value "allow_full_access=true"

      - name: Show AnyDesk Address and Password
        run: |
          $anydeskPath = "D:\\a\\Ballooppower\\Ballooppower\\AnyDesk.exe"
          Start-Process -FilePath $anydeskPath -ArgumentList "--get-id" -NoNewWindow -Wait -Verb RunAs
          Start-Sleep -Seconds 5
          $idFilePath = "$env:APPDATA\\AnyDesk\\ad.id"
          if (Test-Path $idFilePath) {
            $id = Get-Content -Path $idFilePath
            Write-Output "AnyDesk Address: $id"
            Write-Output "AnyDesk Password: Hayat7014@"
          } else {
            Write-Output "AnyDesk ID file not found."
          }
          
